In [1]:
"Hello World"

'Hello World'

In [5]:
greeting = "Hello World"

In [8]:
greeting

'Hello World'

In [10]:
print(greeting)

Hello World


In [12]:
a = 2 

In [14]:
b = 15

In [16]:
a + b

17

In [18]:
my_sum = a + b 

In [22]:
# print sum
my_sum

17

In [24]:
my_product = a + b

In [26]:
# Importing Libraries
import numpy as np

In [28]:
ages_list = [25,30,35,40,45] # this is a python list

In [30]:
ages = np.array(ages_list)

In [31]:
ages

array([25, 30, 35, 40, 45])

In [35]:
# you can also do this in a single line
ages = np.array([25,30,35,40,45,50,55])

In [37]:
# getting specific elements - note that in python, the index starts from 0
ages[0]

25

In [38]:
ages[6]

55

In [41]:
ages[-1] # this is the last element

55

In [43]:
# get subset of elements, based on index range
ages[0:4] # goes from index =0 to 3 (first 4 elements)


array([25, 30, 35, 40])

In [44]:
ages[:4] # goes from beginning to index 3 (same result as above)

array([25, 30, 35, 40])

In [45]:
ages[1:4] # goes from index = 1 to 3 (2nd to 4th element)

array([30, 35, 40])

In [46]:
ages[1:] # goes from index =1 to last element (same result as above) 

array([30, 35, 40, 45, 50, 55])

In [47]:
ages[:] # goes from first to last element (same as ages)

array([25, 30, 35, 40, 45, 50, 55])

In [48]:
ages[::2] # keeps getting every 2nd element only

array([25, 35, 45, 55])

In [49]:
ages[::-1] # reverses the oder of the elemnts

array([55, 50, 45, 40, 35, 30, 25])

In [51]:
#getting the subset of elements, based on a condition 
ages[ages<40]

array([25, 30, 35])

In [52]:
ages[ages<=40]

array([25, 30, 35, 40])

In [54]:
# get no. elements len
len(ages)

7

In [57]:
ages_mean = np.mean(ages)

In [58]:
ages_mean

40.0

In [59]:
np.min(ages)

25

In [60]:
np.max(ages)

55